services:
  springboot_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - devops_SpringBoot_net

networks:
  devops_SpringBoot_net:
    name: devops_SpringBoot_net
    external: true