#Testes Com Estacoes

@base = http://localhost:8080/estacao

### Obter uma estacao
GET {{base}}/1

###Obter todas as estacoes
GET {{base}}

###Obter estacoes por nome
GET {{base}}/name/ana?size=1&page=2&sort=name,asc

###Criar uma estacao
POST {{base}}
Content-Type: application/json

{
    "name": "Antonio Carlos",
    "email": "antoniocarlos@gmail.com",
    "password": "123456",
    "birth": "1995-08-25"

}

### Atualizar uma estacao
PUT {{base}}/15
Content-Type: application/json

{
    "name": "Antonio Olimpio",
    "email": "netinhoalj@gmail.com",
    "password": "123456",
    "birth": "1992-03-25"

}

###Deletar uma estacao
DELETE {{base}}/1